name: create-build-frontend

on:
  push:
    branches: [ "master" ]
    
jobs:
  create-build:
    runs-on: ubuntu-latest
    
    steps:    
      - uses: actions/checkout@v3      
      - name: run yarn build
        run: yarn build
        
        
